import jsPDF from 'jspdf';
import 'jspdf-autotable';

export function generateFieldGuide(ticketData: any, amiText: string, mapImage?: string) {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(20);
    doc.setTextColor(0, 100, 0); // Dark Green
    doc.text("Minnesota 2026 Electronic White Lining", 105, 20, { align: "center" });
    doc.text("Field Compliance Guide", 105, 30, { align: "center" });

    // Ticket Info
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Ticket Number: ${ticketData.ticketNumber || 'N/A'}`, 20, 50);
    doc.text(`Work Start Date: ${ticketData.workToBeginDate || 'N/A'}`, 20, 60);
    doc.text(`Address: ${ticketData.workSiteAddress || 'N/A'}`, 20, 70);

    // AMI
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text("Automated Marking Instructions (AMI)", 20, 90);

    doc.setFontSize(10);
    const splitAMI = doc.splitTextToSize(amiText, 170);
    doc.text(splitAMI, 20, 100);

    let yPos = 100 + (splitAMI.length * 5) + 10;

    // Map Image
    if (mapImage) {
        doc.text("Excavation Map", 20, yPos);
        try {
            doc.addImage(mapImage, 'PNG', 20, yPos + 5, 170, 100);
        } catch (e) {
            console.error("Error adding map image to PDF", e);
            doc.text("(Map Image Error)", 20, yPos + 20);
        }
    }

    // Footer
    doc.setFontSize(8);
    doc.text("Generated by Midwest Underground (MU) Compliance Engine", 105, 280, { align: "center" });

    doc.save(`FieldGuide_${ticketData.ticketNumber || 'draft'}.pdf`);
}
