import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// --- Types ---

export interface CompliancePacketTicketData {
    ticketNumber: string;
    projectAddress: string;
    workStartDate: Date;
    expirationDate: Date;
    legalStartDateTime: Date; // 48h calc
    excavatorName: string;
    ticketType: string;
}

export interface CompliancePacketEWLData {
    geometryType: 'Polygon' | 'Point';
    areaAcres?: number;
    description: string;
    isElectronicOnly: boolean;
    photoUrls: string[];
}

export interface CompliancePacketEvent {
    timestamp: Date;
    user: string;
    action: string;
    details: string;
    eventId: string;
}

export interface CompliancePacketData {
    meta: {
        generatedAt: Date;
        generatedBy: string;
    };
    ticket: CompliancePacketTicketData;
    ewl: CompliancePacketEWLData;
    events: CompliancePacketEvent[];
}

// --- Generator ---

export async function generateCompliancePacketPDF(data: CompliancePacketData): Promise<Blob> {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // 1. Cover Page
    doc.setFontSize(22);
    doc.text("MN 216D Compliance Record", pageWidth / 2, 40, { align: 'center' });

    doc.setFontSize(14);
    doc.text(`Ticket #${data.ticket.ticketNumber}`, pageWidth / 2, 60, { align: 'center' });
    doc.text(`Generated: ${data.meta.generatedAt.toLocaleString()}`, pageWidth / 2, 70, { align: 'center' });

    doc.setFontSize(10);
    doc.text("Generated by MU Platform", pageWidth / 2, 280, { align: 'center' });

    doc.addPage();

    // 2. Ticket Details
    doc.setFontSize(16);
    doc.text("Ticket Details", 14, 20);

    const ticketRows = [
        ['Ticket Number', data.ticket.ticketNumber],
        ['Address', data.ticket.projectAddress],
        ['Excavator', data.ticket.excavatorName],
        ['Work Start', data.ticket.workStartDate.toLocaleString()],
        ['Legal Dig Start', data.ticket.legalStartDateTime.toLocaleString()],
        ['Expires', data.ticket.expirationDate.toLocaleString()],
    ];

    autoTable(doc, {
        startY: 30,
        head: [['Field', 'Value']],
        body: ticketRows,
    });

    // 3. Electronic White Lining
    let yPos = (doc as any).lastAutoTable.finalY + 20;
    doc.setFontSize(16);
    doc.text("Electronic White Lining (EWL)", 14, yPos);
    yPos += 10;

    doc.setFontSize(12);
    doc.text(`Description: ${data.ewl.description}`, 14, yPos, { maxWidth: 180 });
    yPos += 20;

    if (data.ewl.isElectronicOnly) {
        doc.setTextColor(200, 0, 0); // Red warning/notice
        doc.text("Note: Electronic White Lining used in lieu of physical markings (per MN 216D.05(c)).", 14, yPos);
        doc.setTextColor(0, 0, 0);
        yPos += 10;
    }

    // Placeholder for Map Image
    doc.setDrawColor(200);
    doc.rect(14, yPos, 180, 80);
    doc.text("[Map Snapshot Placeholder]", 105, yPos + 40, { align: 'center' });

    doc.addPage();

    // 4. Compliance Log
    doc.setFontSize(16);
    doc.text("Compliance Audit Log", 14, 20);

    const eventRows = data.events.map(e => [
        e.timestamp.toLocaleString(),
        e.action,
        e.user,
        e.details
    ]);

    autoTable(doc, {
        startY: 30,
        head: [['Time', 'Action', 'User', 'Details']],
        body: eventRows,
    });

    return doc.output('blob');
}
