"use client";

import React from 'react';
import { Button } from "@/components/ui/button";
import { FileDown } from "lucide-react";
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface PlannedRod {
    id: string;
    length: number;
    pitch: number;
    azimuth: number;
    pullback?: number;
    pMax?: number;
}

interface PlanSettings {
    diameter: number;
    material: 'HDPE' | 'Steel';
    soil: 'Clay' | 'Sand' | 'Rock';
    declination: number;
}

interface PDFExportButtonProps {
    rods: PlannedRod[];
    settings: PlanSettings;
    projectName?: string;
}

export default function PDFExportButton({ rods, settings, projectName = "Drill Plan" }: PDFExportButtonProps) {

    const handleExport = () => {
        const doc = new jsPDF();

        // Header
        doc.setFontSize(18);
        doc.text(projectName, 14, 22);

        doc.setFontSize(11);
        doc.setTextColor(100);
        doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 30);
        doc.text(`Settings: ${settings.diameter}" ${settings.material} | ${settings.soil} | Declination: ${settings.declination}°`, 14, 36);

        // Table Data
        const tableData = rods.map((rod, index) => [
            index + 1,
            rod.length.toFixed(1),
            rod.pitch.toFixed(1),
            rod.azimuth.toFixed(1),
            rod.pullback ? Math.round(rod.pullback).toLocaleString() : '-',
            rod.pMax ? Math.round(rod.pMax).toLocaleString() : '-'
        ]);

        // Table
        autoTable(doc, {
            head: [['Rod #', 'Length (ft)', 'Pitch (°)', 'Azimuth (°)', 'Pullback (lb)', 'P_max (psi)']],
            body: tableData,
            startY: 44,
            theme: 'grid',
            headStyles: { fillColor: [41, 128, 185], textColor: 255 },
            styles: { fontSize: 10, cellPadding: 3 },
            columnStyles: {
                0: { cellWidth: 20, halign: 'center' },
                4: { fontStyle: 'bold', halign: 'right' },
                5: { fontStyle: 'bold', halign: 'right' }
            }
        });

        // Footer
        const pageCount = doc.getNumberOfPages();
        doc.setFontSize(8);
        doc.setTextColor(150);
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.text('Generated by Midwest Underground', 14, doc.internal.pageSize.height - 10);
            doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 25, doc.internal.pageSize.height - 10);
        }

        // Save
        doc.save(`${projectName.replace(/\s+/g, '_')}_Plan.pdf`);
    };

    return (
        <Button size="sm" variant="outline" onClick={handleExport} className="gap-2">
            <FileDown className="w-4 h-4" />
            Export PDF
        </Button>
    );
}
